# Generated by Django 5.2 on 2025-04-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoraPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated.')),
                ('question', models.TextField(help_text='Enter the main question or topic for discussion.')),
                ('image', models.ImageField(blank=True, help_text='Optional: Upload an image related to the question.', null=True, upload_to='quora_post/')),
                ('created_by', models.ForeignKey(help_text='User who created this object.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who posted the question.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoraReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated.')),
                ('answer', models.TextField(help_text='Enter your reply or answer to the question.')),
                ('image', models.ImageField(blank=True, help_text='Optional: Upload an image related to your reply.', null=True, upload_to='quora_replies/')),
                ('created_by', models.ForeignKey(help_text='User who created this object.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, help_text='Users who liked this reply.', related_name='liked_answers', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The original post this reply belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='quora.quorapost')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who replied to the post.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
